create extension if not exists pgcrypto;

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.sync_expense_report_total()
returns trigger
language plpgsql
as $$
declare
  target_report_id uuid;
begin
  if tg_op = 'DELETE' then
    target_report_id := old.report_id;
  else
    target_report_id := new.report_id;
  end if;

  update public.expense_reports
  set
    total_amount_thb = coalesce(
      (
        select sum(amount_thb)
        from public.expense_items
        where report_id = target_report_id
      ),
      0
    ),
    updated_at = timezone('utc', now())
  where id = target_report_id;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  employee_code text,
  department text,
  cost_center text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_companies (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  company_name text not null check (length(trim(company_name)) > 0),
  logo_data_url text not null check (length(trim(logo_data_url)) > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.expense_types (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text not null,
  description text,
  requires_receipt boolean not null default true,
  is_active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.expense_reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  expense_date date not null,
  company_id uuid references public.user_companies (id) on delete set null,
  company_name text not null check (length(trim(company_name)) > 0),
  company_logo_data_url text,
  export_language text not null default 'en' check (
    export_language in ('en', 'th')
  ),
  employee_name text,
  department text,
  cost_center text,
  note text,
  status text not null default 'draft' check (
    status in ('draft', 'submitted', 'approved', 'rejected', 'exported')
  ),
  total_amount_thb numeric(12, 2) not null default 0 check (total_amount_thb >= 0),
  submitted_at timestamptz,
  exported_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, expense_date)
);

create table if not exists public.expense_items (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.expense_reports (id) on delete cascade,
  expense_type_id bigint references public.expense_types (id),
  expense_type_label text not null,
  amount_thb numeric(12, 2) not null check (amount_thb > 0),
  remark text,
  line_number integer not null default 1 check (line_number > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.expense_receipts (
  id uuid primary key default gen_random_uuid(),
  expense_item_id uuid not null references public.expense_items (id) on delete cascade,
  bucket_name text not null default 'expense-receipts',
  object_path text not null unique,
  original_file_name text not null,
  mime_type text,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes > 0),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.expense_reports
  add column if not exists company_id uuid references public.user_companies (id) on delete set null;

alter table public.expense_reports
  add column if not exists company_logo_data_url text;

alter table public.expense_reports
  add column if not exists export_language text not null default 'en' check (
    export_language in ('en', 'th')
  );

alter table public.expense_reports
  add column if not exists exported_at timestamptz;

create index if not exists user_companies_user_created_idx
  on public.user_companies (user_id, created_at desc);

create index if not exists expense_reports_user_date_idx
  on public.expense_reports (user_id, expense_date desc);

create index if not exists expense_reports_company_idx
  on public.expense_reports (company_id);

create index if not exists expense_items_report_line_idx
  on public.expense_items (report_id, line_number);

create index if not exists expense_receipts_item_idx
  on public.expense_receipts (expense_item_id);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_user_companies_updated_at on public.user_companies;
create trigger set_user_companies_updated_at
before update on public.user_companies
for each row
execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_expense_reports_updated_at on public.expense_reports;
create trigger set_expense_reports_updated_at
before update on public.expense_reports
for each row
execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_expense_items_updated_at on public.expense_items;
create trigger set_expense_items_updated_at
before update on public.expense_items
for each row
execute function public.set_current_timestamp_updated_at();

drop trigger if exists sync_expense_report_total_on_change on public.expense_items;
create trigger sync_expense_report_total_on_change
after insert or update or delete on public.expense_items
for each row
execute function public.sync_expense_report_total();

insert into public.expense_types (
  code,
  label,
  description,
  sort_order
)
values
  ('transportation', 'Transportation', 'Taxi, BTS, MRT, bus, parking, ride-hailing', 10),
  ('client_food', 'Client food', 'Meals or refreshments for customer-facing meetings', 20),
  ('gas', 'Gas', 'Fuel reimbursements for business travel', 30),
  ('toll_fee', 'Toll fee', 'Road, expressway, and bridge toll costs', 40),
  ('misc', 'Miscellaneous', 'Temporary fallback for new expense categories', 50)
on conflict (code) do update
set
  label = excluded.label,
  description = excluded.description,
  sort_order = excluded.sort_order,
  is_active = true;

alter table public.profiles enable row level security;
alter table public.user_companies enable row level security;
alter table public.expense_types enable row level security;
alter table public.expense_reports enable row level security;
alter table public.expense_items enable row level security;
alter table public.expense_receipts enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can manage own companies" on public.user_companies;
create policy "Users can manage own companies"
on public.user_companies
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Authenticated users can read expense types" on public.expense_types;
create policy "Authenticated users can read expense types"
on public.expense_types
for select
to authenticated
using (is_active = true);

drop policy if exists "Users can manage own reports" on public.expense_reports;
create policy "Users can manage own reports"
on public.expense_reports
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can manage own expense items" on public.expense_items;
create policy "Users can manage own expense items"
on public.expense_items
for all
to authenticated
using (
  exists (
    select 1
    from public.expense_reports
    where public.expense_reports.id = report_id
      and public.expense_reports.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.expense_reports
    where public.expense_reports.id = report_id
      and public.expense_reports.user_id = auth.uid()
  )
);

drop policy if exists "Users can manage own receipts" on public.expense_receipts;
create policy "Users can manage own receipts"
on public.expense_receipts
for all
to authenticated
using (
  exists (
    select 1
    from public.expense_items
    join public.expense_reports
      on public.expense_reports.id = public.expense_items.report_id
    where public.expense_items.id = expense_item_id
      and public.expense_reports.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.expense_items
    join public.expense_reports
      on public.expense_reports.id = public.expense_items.report_id
    where public.expense_items.id = expense_item_id
      and public.expense_reports.user_id = auth.uid()
  )
);

comment on table public.profiles is
  'Authenticated user profile metadata for reimbursement exports.';

comment on table public.user_companies is
  'Reusable company identities for export headers. Logos are stored as data URLs for the current scope.';

comment on table public.expense_reports is
  'One reimbursement form per user per day, including export language and company snapshots.';

comment on table public.expense_items is
  'Line items inside a daily reimbursement form. expense_type_label stores a snapshot for history.';

comment on table public.expense_receipts is
  'Receipt image metadata. Store the files in a private Supabase Storage bucket named expense-receipts.';

comment on column public.expense_receipts.object_path is
  'Recommended path: <user_id>/<report_id>/<expense_item_id>/<original_file_name>.';
